### ISSUE TITLE
Selectively heat bazel remote cache

### ISSUE THREAD

**Issue by mihaigalos** [buchgr/bazel-remote#289] opened 2020-06-05 10:07 UTC
On a bazel remote cache server, I noticed the cache gets "heated" (PUT, green) a whole lote more than it is used (GET, cyan) :
![grafik](https://user-images.githubusercontent.com/16443090/83863895-48c8c580-a724-11ea-9d7d-12e252c1df4b.png)

Is there a way to somehow selectively/automatically set the `--remote_upload_local_results` to true or false?

What I envisioned is something like (sorry for the mix of bash and C++ in .bazelrc..):
```bazelrc
#.bazelrc
build:myconfig --remote_upload_local_results=$(if time.hour % 2 ? true:false)
```

Calling `bazel build --config=myconfig //...` would thus only enable updating/heating the remote cache evey 2nd hour.

Manually invoking `bazel` with the if logic above would not be an option, because the config needs to be adminitstered centrally in `.bazelrc`.

**Comment by mostynb** [comment] 2020-06-05 19:51
I'm not particularly familiar with bazel's config options, but this graph doesn't look good. I wonder why bazel is uploading so much in the first place?

Is your cache too small for the artifacts that are being stored there? ie are cache items like to be expired from the cache before they're used, and re-uploaded?

Or maybe your build is not reproducible enough, so bazel gets very few cache hits?

**Comment by mihaigalos** [comment] 2020-06-08 13:24
> Is your cache too small for the artifacts that are being stored there?

This is a big cache (1.8TB Samsung SSD EVO 860). A lot of clients are using it.
Is the cache reuploading artefacts which are newer than say _threshold_,  even though they still have the same hash?

> Or maybe your build is not reproducible enough, so bazel gets very few cache hits?

This might be the case. But only if the clients had a custom-roller `.bazelrc` on their machines.

**Comment by mostynb** [comment] 2020-06-09 21:28
> This is a big cache (1.8TB Samsung SSD EVO 860). A lot of clients are using it.
Is the cache reuploading artefacts which are newer than say threshold, even though they still have the same hash?

The cache server just provides whichever blobs that the clients ask for (so long as the cache has them). It the AC and CAS hash keyspaces are separate, and only one blob is stored for a given (AC/CAS, hash) pair.

Are you using "builds without the bytes"? That might explain the graph- clients upload all the intermediate and leaf blobs when the cache is cold, but then only download the leaf blobs when the cache is hot.

Can you make a build and report back the cache hit rate? This link might help: https://docs.bazel.build/versions/master/remote-execution-caching-debug.html

**Comment by mostynb** [comment] 2021-05-07 18:39
Closing this issue because I don't have enough details to make any progress. Please reopen if this is still a problem and we can try to dig into it together.

**Closed by mostynb** 2021-05-07 18:39 UTC
