### ISSUE TITLE
Exception thrown with bazel 6.0.0

### ISSUE THREAD

**Issue by nickbreen** [buchgr/bazel-remote#629] opened 2023-01-12 21:11 UTC
Does not prevent a build succeeding.

```WARNING: Remote Cache: CANCELLED: Cancelled by user
java.io.IOException: io.grpc.StatusRuntimeException: CANCELLED: Cancelled by user
	at com.google.devtools.build.lib.remote.GrpcCacheClient.lambda$uploadActionResult$10(GrpcCacheClient.java:295)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:203)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:190)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:133)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:55)
	at com.google.devtools.build.lib.remote.util.RxFutures$2.onError(RxFutures.java:257)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:117)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.onError(SingleUsing.java:180)
	at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:95)
	at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:81)
	at com.google.devtools.build.lib.remote.util.RxFutures$OnceSingleOnSubscribe$1.onFailure(RxFutures.java:172)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.devtools.build.lib.remote.NetworkTimeInterceptor$NetworkTimeCall$1.onClose(NetworkTimeInterceptor.java:81)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$1ClosedByContext.runInContext(ClientCallImpl.java:215)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.grpc.StatusRuntimeException: CANCELLED: Cancelled by user
	at io.grpc.Status.asRuntimeException(Status.java:535)
	... 13 more
Caused by: io.grpc.StatusRuntimeException: CANCELLED: Cancelled by user
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at com.google.devtools.build.lib.remote.ByteStreamUploader$AsyncUpload.cancel(ByteStreamUploader.java:408)
	at com.google.devtools.build.lib.remote.ByteStreamUploader.lambda$startAsyncUpload$1(ByteStreamUploader.java:234)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:851)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:232)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:208)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:167)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:119)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:119)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:49)
	at com.google.devtools.build.lib.remote.util.RxFutures$2.onSuccess(RxFutures.java:249)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:112)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.onSuccess(SingleUsing.java:154)
	at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
	at com.google.devtools.build.lib.remote.util.RxFutures$OnceSingleOnSubscribe$1.onSuccess(RxFutures.java:155)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:49)
	at com.google.devtools.build.lib.remote.ByteStreamUploader$Writer.onCompleted(ByteStreamUploader.java:506)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:476)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	... 5 more
```

**Comment by mostynb** [comment] 2023-01-13 21:19
Hi- thanks for the bug report. I have not been able to reproduce this yet. Could you share your bazel-remote config and bazel flags?

**Comment by mostynb** [comment] 2023-01-15 15:26
Also- which version of bazel-remote are you using, and does it log any errors or warnings when this occurs?

**Comment by nickbreen** [comment] 2023-01-15 20:53
The exception was logged by bazel 6.0.0 after upgrading from 5.x.

We run the cache as the container with a systemd service:

```
[Unit]
Description=Bazel Cache
Requires=docker.service
After=docker.service

[Service]
DynamicUser=yes
ExecStartPre=+docker pull quay.io/bazel-remote/bazel-remote:v2.4.0
ExecStart=+docker run --rm --log-driver=journald --user=%U:%G --publish=9092:9092 --volume=%C/bazel:/data:Z quay.io/bazel-remote/bazel-remote:v2.4.0 --max_size 50
Restart=always
CacheDirectory=bazel

[Install]
WantedBy=multi-user.target
```

We use gRPC and our own installation of OpenJDK11.

```
#.bazelrc
startup --noautodetect_server_javabase
startup --server_javabase=opt/jdk11
common --experimental_allow_tags_propagation
common --incompatible_no_implicit_file_export
common --announce_rc
common --attempt_to_print_relative_paths
common --distdir build/bazel/dist --distdir opt/bazel/derived/distdir
common --noexperimental_repository_disable_download
--experimental_remote_cache_async
--experimental_profile_additional_tasks=upload_time,process_time,local_cpu_usage,system_cpu_usage,local_memory_usage,system_memory_usage,remote_cache_check,remote_download,remote_network
build --verbose_failures
build --remote_local_fallback
build --remote_retries=0
build --nosandbox_default_allow_network
build --experimental_strict_java_deps=strict
build --java_language_version=11
build --tool_java_language_version=11
build --java_runtime_version=11
build --tool_java_runtime_version=11
build --incompatible_strict_action_env
build --use_ijars
build --sandbox_tmpfs_path=/tmp
build --worker_sandboxing
test --test_output=errors
test --test_summary=terse
build --remote_cache=grpc://cactus.nz1.lmax:9092
build --experimental_convenience_symlinks=ignore
build --local_cpu_resources=HOST_CPUS-2
build --local_ram_resources=HOST_RAM*0.5
startup --host_jvm_args=-Xmx2g
```

Of note is probably `build --remote_local_fallback --remote_retries=0 --remote_cache=grpc://a.b.c.d:9092`

Some of us have an additional disk cache configured with `build --disk_cache=/x/y/z/bazel`.

Some of us also include a few extra flags, but their presence/absence does not appear to affect the exception: `--noremote_upload_local_results --incompatible_remote_results_ignore_disk` or `--experimental_build_event_upload_strategy=local --noremote_upload_local_results --incompatible_remote_results_ignore_disk`

**Comment by mostynb** [comment] 2023-01-15 21:37
Are there any errors in the bazel-remote logs?

Also I wonder if you could try using bazel-remote v2.3.9?

**Comment by nickbreen** [comment] 2023-01-15 21:51
We were using 2.3.9 when we first noticed the exceptions, we upgraded to 2.4.0 to make sure we were on the latest version.

Nothing alarming in the bazel-remote log, typical entries below:

```
Jan 16 10:48:55 a.b.c.d docker[3764447]: 2023/01/15 21:48:55 GRPC BYTESTREAM SKIPPED WRITE: uploads/3f29607b-8347-495e-b11c-1ca93dbff271/blobs/fb53af5bc232b09c6fffc7ac69c0086ffb9027803e691351343e147f37dfd05b/5147
Jan 16 10:48:55 a.b.c.d docker[3764447]: 2023/01/15 21:48:55 GRPC BYTESTREAM WRITE COMPLETED: uploads/aecbe1fc-4d3a-4719-b968-b75323e17440/blobs/b9be2cef51b3d821e09459b6d64e2a8b1b55a2991ee33f8a088396abb7547704/148
Jan 16 10:48:55 a.b.c.d docker[3764447]: 2023/01/15 21:48:55 GRPC AC GET 53a9a384349c8d8fb0d6bbf079705f6e60f6a8741ec84e46a05a58c0dd8ea44c NOT FOUND
Jan 16 10:48:55 a.b.c.d docker[3764447]: 2023/01/15 21:48:55 GRPC CAS HEAD 6d6e64633efcedc2e075161d589f2f9849d038bbedb667f9d1dfd34769fc8916 OK
```

**Comment by nickbreen** [comment] 2023-01-16 00:37
We also have this happening with 2.3.7.

We also found in our bazel-remote logs a few errors complaining about the nofiles ulimit. We've added `--ulimit nofile=10240:10240` to the command line for the docker container.

Anecdotally, bazel 6.0.0 seems to spend considerably longer in "remote-cache" while building, my hunch is that it's some configuration in bazel that's behaving differently with 6.0.0 that's the problem.

**Comment by nickbreen** [comment] 2023-01-17 02:10
Anecdotal observation: when bazel reports long times for `remote-cache` when building, bazel-remote appears to have a very large number of threads.

I.e. a freshly restarted bazel-remote instance has a handful of threads (and a small virt size )... after sometime there's a very large number of threads (~5000) and 44GB of virt.

Output from `top` (truncated):

```
3940081 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:00.02      `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                    
3940114 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:01.40          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940115 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:11.52          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940116 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:00.00          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940117 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:11.65          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940118 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:00.00          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940119 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:10.78          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940120 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:12.01          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940121 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:06.59          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940122 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:10.85          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940123 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:13.00          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940124 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:11.48          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940125 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:12.45          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940126 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:11.65          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940127 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:00.00          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940128 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:00.00          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940129 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:00.00          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3940130 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:00.00          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                                                                                                
3941242 root      20   0   44.2g 306260  13144 S   0.0   4.1   0:00.00          `- /app/bazel-remote-base.binary --http_address=:8080 --dir=/data --profile_address=:6060 --max_size 50                 
...
```

**Comment by mostynb** [comment] 2023-01-22 13:36
5000 threads sounds suspiciously close to the maximum limit on concurrent cache evictions: https://github.com/buchgr/bazel-remote/blob/master/cache/disk/load.go#L45

What kind of storage are you using? Is it SSD-like in terms of speed? Your top output snippet mentions a lot of threads in interruptable sleep state (`S`) - are there many in uninterruptible sleep state (`D`) when the number of bazel-remote threads spike?

**Comment by nickbreen** [comment] 2023-01-22 19:57
Our cache is running on a relatively under-powered mini-PC with a SATA SSD dedicated to the cache.

I'm going to guess that the thread count and slowness are due to an under-spec'd system. Given that we have another cache in a different geographic region which is just fine as it's on server-class hardware.

Though both teams experience the exception, only one seems to be experiencing slowness and the thread explosions.

**Comment by mostynb** [comment] 2023-01-23 07:48
I suspect there are multiple things going on here.

If you get a chance to look at htop on the mini-PC when the number of bazel-remote threads spike, if there are lots of threads in `D` state then that would point to storage speed (though either SATA or NVMe SSDs should be fast enough for many use cases). If not, then maybe the CPU is underpowered? Which filesystem are you using?

Oh, and the `--volume=%C...` flag caught my eye- are you running this in WSL?

Since this seems to be a regression between bazel 5 and 6, it might be worth reporting an issue over there too if you haven't already.

**Comment by nickbreen** [comment] 2023-01-23 20:02
FYI CPU is only a Ryzen 3 5300U.

We're running another instance on a more powerful workstation to compare too with a 14/28 Xeon.

It's a systemd unit: hence the % values for the bind mounts.

Filesystem btrfs.

Most of the threads are in an `Ssl` state, a handful in `I`

**Comment by nickbreen** [comment] 2023-01-23 20:42
FYI CPU is only a Ryzen 3 5300U.

We're running another instance on a more powerful workstation to compare with a 14/28 Xeon.

It's a systemd unit: hence the % values for the bind mounts.

Filesystem btrfs.

Will check the thread states when it next goes weird.

**Comment by nickbreen** [comment] 2023-01-24 21:21
The threads are a symptom of an under-resourced host for the cache. Running on a more powerful host does not appear to present the same peak thread count.

The exception logged by bazel is still extant and does not correlate with the performance problem.

**Comment by mostynb** [comment] 2023-01-25 23:13
Interesting- I'll keep an eye on the discussion in the bazel issue.

**Comment by mostynb** [comment] 2023-02-02 21:55
It looks like this is a bazel problem, closing this bazel-remote issue.

**Closed by mostynb** 2023-02-02 21:55 UTC
